library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.FridgeGlobals.all;
use work.FridgeIRCodes.all;

package FridgeRAMBootImage is

constant RAMBootImage : XCM2_RAM :=
(
     -- Generated by falc from /mnt/data/Projects/Spartan6Fridge/fridge/fpga/fridge_spartan6/examples/rom/src/rom_paint.falc.
     -- Do not edit: change the source program and re-run falc.
     --
     -- addr  bytes          instruction
     -- ROM demo: paint the Case B ROM image to the active frame.
     --
     -- VMODE TEXT then EGA (locks the A-bit-0 mode decode), present an
     -- all-zero frame with VPRE MANUAL_11 (displayed and active frames
     -- both frame 1, single-buffered), then walk ROM segments 0..3 with
     -- the device protocol (mode LOAD, segment hi/lo, 256-byte stream)
     -- and paint each ROM byte as one framebuffer byte (two 4bpp pixels)
     -- at the frame pointer HL. Segments are re-selected without a device
     -- reset (the stream's end returns the device to the mode state).
     -- 4 * 256 = 1024 bytes are painted at frame bytes 0..1023; the rest
     -- of the frame stays at its reset value (black). HLT when done.
     16#00# => MVI_A,        -- MVI A, 1
     16#01# => X"01",
     16#02# => VMODE,        -- VMODE
     16#03# => MVI_A,        -- MVI A, 0
     16#04# => X"00",
     16#05# => VMODE,        -- VMODE
     -- present: VPRE MANUAL_11 (A = 5): visible = 1, active = 1
     16#06# => MVI_H,        -- MVI H, 0
     16#07# => X"00",
     16#08# => MVI_L,        -- MVI L, 0
     16#09# => X"00",
     16#0A# => MVI_A,        -- MVI A, 5
     16#0B# => X"05",
     16#0C# => VPRE,         -- VPRE
     -- ROM reset (device 2, value 1)
     16#0D# => MVI_A,        -- MVI A, 1
     16#0E# => X"01",
     16#0F# => IOUT,         -- OUT 2
     16#10# => X"02",
     16#11# => MVI_D,        -- MVI D, 0
     16#12# => X"00",
     16#13# => MVI_A,        -- MVI A, 2
     16#14# => X"02",
     16#15# => IOUT,         -- OUT 1
     16#16# => X"01",
     16#17# => MVI_A,        -- MVI A, 0
     16#18# => X"00",
     16#19# => IOUT,         -- OUT 1
     16#1A# => X"01",
     16#1B# => MOV_AD,       -- MOV A, D
     16#1C# => IOUT,         -- OUT 1
     16#1D# => X"01",
     -- stream 256 bytes to the frame at HL
     16#1E# => MVI_C,        -- MVI C, 0
     16#1F# => X"00",
     16#20# => IIN,          -- IN 1
     16#21# => X"01",
     16#22# => VFSA,         -- VFSA
     16#23# => INX_HL,       -- INX HL
     16#24# => DCR_C,        -- DCR C
     16#25# => JNZ,          -- JNZ byte_loop
     16#26# => X"00",
     16#27# => X"20",
     16#28# => INR_D,        -- INR D
     16#29# => MOV_AD,       -- MOV A, D
     16#2A# => CPI,          -- CPI 4
     16#2B# => X"04",
     16#2C# => JNZ,          -- JNZ segment_loop
     16#2D# => X"00",
     16#2E# => X"13",
     16#2F# => HLT,          -- HLT
     others => X"00"
);
end FridgeRAMBootImage;
