library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.FridgeGlobals.all;
use work.FridgeIRCodes.all;

package FridgeRAMBootImage is

constant RAMBootImage : XCM2_RAM :=
(
     -- Generated by falc from /mnt/data/Projects/Spartan6Fridge/fridge/fpga/fridge_spartan6/examples/palette/src/vpal_contract.falc.
     -- Do not edit: change the source program and re-run falc.
     --
     -- addr  bytes          instruction
     -- CPU VPAL ABI test: all byte indices, flags and registers, slow GPU.
     16#00# => MVI_A,        -- MVI A, 0xFF
     16#01# => X"FF",
     16#02# => ADI,          -- ADI 1
     16#03# => X"01",
     16#04# => LDA,          -- LDA TestIndex
     16#05# => X"00",
     16#06# => X"42",
     16#07# => MVI_B,        -- MVI B, 0x12
     16#08# => X"12",
     16#09# => MVI_C,        -- MVI C, 0x34
     16#0A# => X"34",
     16#0B# => MVI_D,        -- MVI D, 0x56
     16#0C# => X"56",
     16#0D# => MVI_E,        -- MVI E, 0x78
     16#0E# => X"78",
     16#0F# => LXI_HL,       -- LXI HL, 0x9ABC
     16#10# => X"9A",
     16#11# => X"BC",
     16#12# => VPAL,         -- VPAL
     16#13# => STA,          -- STA 0xF000
     16#14# => X"F0",
     16#15# => X"00",
     16#16# => MOV_AB,       -- MOV A, B
     16#17# => STA,          -- STA 0xF001
     16#18# => X"F0",
     16#19# => X"01",
     16#1A# => MOV_AC,       -- MOV A, C
     16#1B# => STA,          -- STA 0xF002
     16#1C# => X"F0",
     16#1D# => X"02",
     16#1E# => MOV_AD,       -- MOV A, D
     16#1F# => STA,          -- STA 0xF003
     16#20# => X"F0",
     16#21# => X"03",
     16#22# => MOV_AE,       -- MOV A, E
     16#23# => STA,          -- STA 0xF004
     16#24# => X"F0",
     16#25# => X"04",
     16#26# => MOV_AH,       -- MOV A, H
     16#27# => STA,          -- STA 0xF005
     16#28# => X"F0",
     16#29# => X"05",
     16#2A# => MOV_AL,       -- MOV A, L
     16#2B# => STA,          -- STA 0xF006
     16#2C# => X"F0",
     16#2D# => X"06",
     16#2E# => PUSH_AF,      -- PUSH AF
     16#2F# => POP_HL,       -- POP HL
     16#30# => MOV_AL,       -- MOV A, L
     16#31# => STA,          -- STA 0xF007
     16#32# => X"F0",
     16#33# => X"07",
     16#34# => LDA,          -- LDA TestIndex
     16#35# => X"00",
     16#36# => X"42",
     16#37# => INR_A,        -- INR A
     16#38# => STA,          -- STA TestIndex
     16#39# => X"00",
     16#3A# => X"42",
     16#3B# => JNZ,          -- JNZ loop
     16#3C# => X"00",
     16#3D# => X"00",
     16#3E# => HLT,          -- HLT
     16#3F# => JMP,          -- JMP
     16#40# => X"00",
     16#41# => X"00",
     16#42# => X"00",        -- static TestIndex
     others => X"00"
);
end FridgeRAMBootImage;
